language: c

sudo: required

script:
  - export TRAVIS="true"
  - make

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh aptget_install pandoc
  - ./travis-tool.sh aptget_install pandoc-citeproc
  - ./travis-tool.sh aptget_install texlive-latex-recommended
  - ./travis-tool.sh aptget_install texlive-xetex
  - ./travis-tool.sh aptget_install texlive-luatex
  - ./travis-tool.sh aptget_install pandoc-citeproc
  - ./travis-tool.sh aptget_install etoolbox
  - ./travis-tool.sh aptget_install texlive-latex-extra
  - ./travis-tool.sh install_r mapproj
  - ./travis-tool.sh install_github fmichonneau/splits/pkg
  - ./travis-tool.sh install_github fmichonneau/chopper
  - ./travis-tool.sh install_github fmichonneau/phyloch
  - ./travis-tool.sh install_github richfitz/storr
  - ./travis-tool.sh install_github richfitz/remake
  - ./travis-tool.sh install_github yihui/tikzDevice